env:
  global:
    - TEST_DEPENDS=pytest
    - MB_ML_VER=2010
    # Put wheels where travis expects them to be
    - WHEEL_SDIR=dist

language: python

services: docker
sudo: required
dist: xenial

matrix:
  fast_finish: true
  include:
    # - name: Python 2.7
    #   python: 2.7
    # - name: Python 3.5
    #   python: 3.5
    #   env:
    #     - BOOST_PYTHON=boost_python-py35
    # - name: Python 3.6
    #   python: 3.6
    #   env:
    #     - BOOST_PYTHON=boost_python-py35
    - name: Python 3.7
      python: 3.7
      env:
        - BOOST_PYTHON=boost_python-py35

before_install:
  - git clone https://github.com/matthew-brett/multibuild
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - build_wheel . x86_64

script:
  - install_run x86_64

before_deploy:
  # "python setup.py sdist" is called automatically by the deploy step, so
  # replace it with an empty file so we don't ruin our hard work
  - rm setup.py
  - touch setup.py
